# Generated by Django 5.2.5 on 2025-09-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activos',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Tipo_activo',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
