# Generated by Django 5.2.5 on 2025-09-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0002_delete_activos_delete_empleado_delete_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_activo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.empleado')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estado')),
                ('Tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tipo_activo')),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.ubicacion')),
            ],
        ),
    ]
